name: 'Git tag'
description: 'Automated git tag on PR merge'
author: 'Clément Doucy'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  github_token:
    description: GitHub token to authenticate against GitHub API
    required: true

outputs:
  tag:
    description: 'The publish git tag'

runs:
  using: node20
  main: dist/index.js
